import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Inter, Arsenal } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter", // This creates a CSS variable
});

const arsenal = Arsenal({
  subsets: ["latin"],
  weight: ["400", "700"], // Specify the weights you need
  display: "swap",
  variable: "--font-arsenal", // This creates another CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${arsenal.variable}`}>
        {children}
      </body>
    </html>
  );
}
